### PR TITLE
[Improve] [Seatunnel-Web] Add support for Seatunnel 2.3.6 in Seatunnel-Web

### PR DESCRIPTION
**Pull request by arshadmohammad**
## Purpose of this pull request
Add support for Seatunnel 2.3.5 in Seatunnel-Web.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs

Build seatunnel-web with the proposed the code changes, installed  and verified that jobs are successfully executed on seatunnel 2.3.5 engines. Verification snapshot attached

image

### CODE REVIEW

**Comment by hooklee2000** [comment]
Well done. It also works well with  seatunnel tag 2.3.6.

**Comment by arshadmohammad** [comment]
@hailin0, @hooklee2000 Thanks for your feedback. is there anything else I can do to get this PR merged.

**Comment by arshadmohammad** [comment]
I will check why CI is failing.

**Comment by arshadmohammad** [comment]
I have changed seatunnel version to 2.3.6. Now seatunnel-ui started failing in PR CI. Seems the failure not related to this change but need to find out root cause of build failure.

`[INFO] src/layouts/dashboard/index.tsx(75,40): error TS2339: Property '$route' does not exist on type 'CreateComponentPublicInstance<{}, { showSide: Ref<boolean, boolean>; menuKey: Ref<string, string>; }, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 12 more ..., {}>'.`
`Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (build) on project seatunnel-web-dist: Failed to run task: 'npm run build:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1`

Does anybody have any idea on this build failure?

**Comment by twenty-zhang** [comment]
Try this.
`<router-view key={this['$route'].fullPath} class={!this.showSide && 'px-32 py-12'} />`

**Comment by arshadmohammad** [comment]
Thanks @twenty-zhang, the changes you suggested works fine.
Most of the PR sanity checks are passed now
Build and verified the changes locally. installed seatunnel and seatunnel-web. created and executed on job. job executed successfully.

**Comment by arshadmohammad** [comment]
image

**Comment by arshadmohammad** [comment]
I will check why junit tests are failing with java 8

**Comment by arshadmohammad** [comment]
Seems Backend / Unit Test (8, ubuntu-latest) (pull_request) is failign becuase of CI environment issue, seatunnel-jackson-2.3.6-optional.jar; is corrupted
` [INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project seatunnel-dynamicform: Compilation failure: Compilation failure: 
Error: [ERROR] error reading /home/runner/.m2/repository/org/apache/seatunnel/seatunnel-jackson/2.3.6/seatunnel-jackson-2.3.6-optional.jar; zip file is empty`

**Comment by arshadmohammad** [comment]
pushed dummy change to retrigger the ci

**Comment by arshadmohammad** [comment]
CI is passed :-)

**Review by Hisoka-X — APPROVED** [review]

**Comment by arshadmohammad** [comment]
Thanks @Hisoka-X for reviewing and merging the PR.
